### ISSUE TITLE
java.lang.VerifyError: net/glxn/qrgen/android/QRCode

### ISSUE THREAD

**Issue by kongqw** [kenglxn/QRGen#86]
I use this to make bitmap
``` java
Bitmap qrCode = QRCode.from(macAddress).withSize(200, 200).bitmap();
imageView.setImageBitmap(qrCode);
```

but show error:

``` log
java.lang.VerifyError: net/glxn/qrgen/android/QRCode
    at com.bitmain.bmrobot.activity.MainActivity.onOptionsItemSelected(MainActivity.java:198)
    at android.app.Activity.onMenuItemSelected(Activity.java:2607)
    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:107)
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:107)
    at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:777)
    at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:817)
    at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:964)
    at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
    at android.widget.AdapterView.performItemClick(AdapterView.java:299)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1115)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2928)
    at android.widget.AbsListView$3.run(AbsListView.java:3691)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5028)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kenglxn** [comment]
You need to supply more information if you want someone to be able to help you with this. 
What is your build environment, target platform (i.e. android version)? etc.

**Comment by kongqw** [comment]
I've solved it, thx, it‘s by myself.
